In [1]:
pip install -e .


Obtaining file:///home/darkspartan345/RL_tic_tac_toe/OpenAI-Gym-TicTacToe-Environment
  Preparing metadata (setup.py) ... done
  Attempting uninstall: gym-TicTacToe
    Found existing installation: gym-TicTacToe 0.1
    Uninstalling gym-TicTacToe-0.1:
      Successfully uninstalled gym-TicTacToe-0.1
  Running setup.py develop for gym-TicTacToe
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install tabulate

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import gymnasium as gym
import gym_TicTacToe  # Asegúrate que esté registrado

env = gym.make("TicTacToe-v0", render_mode="human", small=-1, large=10)

In [22]:
# get 10 randomly sampled actions (between 0 and 8)
[env.action_space.sample() for _ in range(10)]

[1, 7, 2, 8, 6, 8, 6, 3, 3, 4]

In [23]:
# get 10 randomly sampled states
[env.observation_space.sample() for _ in range(10)]

[3727, 7746, 5308, 1972, 7802, 6343, 1918, 6273, 6540, 8773]

In [24]:
env.reset()
print(env.render())

╒═══╤═══╤═══╕
│ - │ - │ - │
├───┼───┼───┤
│ - │ - │ - │
├───┼───┼───┤
│ - │ - │ - │
╘═══╧═══╧═══╛


In [25]:
color = 1 # player 1
action = 4

new_state, reward, done, _ = env.step((action, color))
print(new_state, reward, done)
print(env.render())

AttributeError: module 'numpy' has no attribute 'bool8'

In [ ]:
color = 2 # player 2
action = 0
new_state, reward, done, _ = env.step((action, color))
print(new_state, reward, done)
print(env.render())

[[2 0 0]
 [0 1 0]
 [0 0 0]] -1 False
╒═══╤═══╤═══╕
│ O │ - │ - │
├───┼───┼───┤
│ - │ X │ - │
├───┼───┼───┤
│ - │ - │ - │
╘═══╧═══╧═══╛


In [ ]:
state_size = env.observation_space.n
action_size = env.action_space.n
print(state_size, action_size)

8953 9
