In [21]:
pip install -e gym_TicTacToe/


Obtaining file:///home/darkspartan345/Documentos/GitHub/OpenAI-Gym-TicTacToe-Environment/gym_TicTacToe
  Preparing metadata (setup.py) ... done
  Attempting uninstall: gym_TicTacToe
    Found existing installation: gym_TicTacToe 0.1
    Uninstalling gym_TicTacToe-0.1:
      Successfully uninstalled gym_TicTacToe-0.1
  DEPRECATION: Legacy editable install of gym_TicTacToe==0.1 from file:///home/darkspartan345/Documentos/GitHub/OpenAI-Gym-TicTacToe-Environment/gym_TicTacToe (setup.py develop) is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for gym_TicTacToe
Note: you may need to restart the kernel to use updated 

In [22]:
pip install tabulate

Note: you may need to restart the kernel to use updated packages.


In [23]:
import gymnasium as gym
import gym_TicTacToe  # Asegúrate que esté registrado

env = gym.make("TicTacToe-v0", render_mode="human", small=-1, large=10)

In [24]:
# get 10 randomly sampled actions (between 0 and 8)
[env.action_space.sample() for _ in range(10)]

[np.int64(7),
 np.int64(3),
 np.int64(0),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(1)]

In [25]:
# get 10 randomly sampled states
[env.observation_space.sample() for _ in range(10)]

[array([2, 1, 0, 1, 0, 2, 2, 0, 1]),
 array([0, 1, 2, 2, 2, 0, 0, 0, 0]),
 array([1, 2, 0, 1, 1, 1, 1, 1, 1]),
 array([2, 1, 1, 0, 0, 2, 0, 2, 1]),
 array([2, 2, 1, 1, 0, 0, 2, 0, 2]),
 array([1, 2, 1, 0, 0, 2, 0, 2, 1]),
 array([2, 0, 2, 1, 1, 1, 2, 0, 1]),
 array([1, 2, 0, 1, 1, 2, 2, 1, 1]),
 array([2, 2, 0, 1, 0, 0, 0, 2, 1]),
 array([1, 0, 0, 0, 2, 0, 0, 1, 0])]

In [26]:
env.reset()
env.render()

╒═══╤═══╤═══╕
│ - │ - │ - │
├───┼───┼───┤
│ - │ - │ - │
├───┼───┼───┤
│ - │ - │ - │
╘═══╧═══╧═══╛


In [27]:
color = 1 # player 1
action = 4

new_state, reward, done,truncated, _ = env.step(action)
print(new_state, reward, done)
env.render()

[0 0 0 0 1 0 0 0 0] -1 False
╒═══╤═══╤═══╕
│ - │ - │ - │
├───┼───┼───┤
│ - │ X │ - │
├───┼───┼───┤
│ - │ - │ - │
╘═══╧═══╧═══╛


In [28]:

action = 0
new_state, reward, done,truncated, _ = env.step(action)
print(new_state, reward, done)
env.render()

[2 0 0 0 1 0 0 0 0] -1 False
╒═══╤═══╤═══╕
│ O │ - │ - │
├───┼───┼───┤
│ - │ X │ - │
├───┼───┼───┤
│ - │ - │ - │
╘═══╧═══╧═══╛


In [30]:
state_size = env.observation_space
action_size = env.action_space.n
print(state_size, action_size)

Box(0, 2, (9,), int64) 9
